#!/bin/bash

#DIRCOLORS
WORKDIR=`git rev-parse --show-toplevel`
cp $WORKDIR/templates/dircolors $HOME/.dircolors

gsettings set "org.gnome.desktop.interface" "monospace-font-name" "Liberation Mono 10"

gsettings set "org.gnome.Terminal.Legacy.Settings" "menu-accelerator-enabled" "false"
gsettings set "org.gnome.Terminal.Legacy.Settings" "default-show-menubar" "false"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "close-tab" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "close-window" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "copy" "<Ctrl><Shift>c"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "detach-tab" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "find" "<Control><Shift>F"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "find-clear" "<Control><Shift>J"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "find-next" "<Control><Shift>G"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "find-previous" "<Control><Shift>H"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "full-screen" "F11"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "help" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "move-tab-left" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "move-tab-right" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "new-profile" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "new-tab" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "new-window" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "next-tab" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "paste" "<Ctrl><Shift>v"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "prev-tab" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "reset" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "reset-and-clear" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "save-contents" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-1"  "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-2"  "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-3"  "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-4"  "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-5"  "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-6"  "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-7"  "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-8"  "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-9"  "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-10" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-11" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-12" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-13" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-14" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-15" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-16" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-17" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-18" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-19" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-20" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-21" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-22" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-23" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-24" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-25" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-26" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-27" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-28" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-29" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-30" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-31" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-32" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-33" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-34" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-35" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "switch-to-tab-35" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "toggle-menubar" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "zoom-in" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "zoom-normal" "disabled"
gsettings set "org.gnome.Terminal.Legacy.Keybindings:/" "zoom-out" "disabled"
